sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t shanta280/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shanta280/react-test npm run test -- --coverage


after_success:
  - docker build -t shanta280/multi-client ./client
  - docker build -t shanta280/multi-nginx ./nginx
  - docker build -t shanta280/multi-server ./server
  - docker build -t shanta280/multi-worker ./worker

